# Generated by Django 4.2 on 2023-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_survey', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('money', 'Money'), ('hidden', 'Hidden')], default='text', max_length=10),
        ),
    ]
