# Generated by Django 4.2 on 2023-05-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_survey', '0004_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
